---

- name: Deploy the latest Flask app
  hosts: localhost
  tasks:

  - name: Stop the running container
    docker_container:
     name: flask
     state: stopped
     image: seebraz/python

  - name: Remove the stopped container
    docker_container:
     name: flask
     state: absent

  - name: Pull the latest image from docker hub
    docker_image:
     name: seebraz/python
     tag: latest
     source: pull

  - name: Run the container with the latest image
    docker_container:
     name: flask
     image: seebraz/python:latest
     state: started
     detach: yes
     tty: yes
     ports: [8000:7000]
     restart_policy: always
