services:
  flask:
    image: apurwasingh/flask
    container_name: flask
    ports:
      - "8001:7000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
